### ISSUE TITLE
Updated the alternate boss-key script

### ISSUE THREAD

**Issue by detuur** [sibwaf/mpv-scripts#1]
Hey I just wanted to let you know that I've updated my boss-key script you linked in your README. I've eliminated the time lag and it's cross-platform now. It lives in a proper repo now: https://github.com/detuur/mpv-scripts

Do you think it'd be interesting to add a blackout as well? 
Also sorry for mucking up your issue tracker but it was the only way I could find for getting to you.

Cheers

**Comment by sibwaf** [comment]
Sorry, doesn't seem like it is working for me. Only pause is being applied. By no means I'm a Lua programmer, but line 29 seems kind of strange (two dots before 'utils') to me. Though, "fixing" it broke even the key binding. I'm on Windows 10, so yeah, more fun with Microsoft's abomination.

You can use blackout's code as you wish. Though remember - it doesn't really work everywhere. For example, I tested (don't ask why) it in a VM with default mpv configuration, and it did nothing at all.

**Comment by detuur** [comment]
The double dot is intentional, it's a string concatentation. And yeah I'm at the end of my rope when it comes to this. I'm on Windows 10 too but this shit keeps breaking in the oddest ways. This finally works consistently on my end though. Thanks for the feedback, I'll see if other people are having trouble as well. Whatever solution I come up with next is definitely not going to be in Powershell.

**Comment by detuur** [comment]
Hey I think I found the reason why it wasn't working. There was a debug instruction in there referencing a fixed path, which doesn't exist on your system (unless you've got `R:\pipedebug\` on your sys for some reason). Care to give it another try?

**Comment by sibwaf** [comment]
Yup, it works just fine now. Adding blackout might be a good idea, actually.

**Comment by detuur** [comment]
Thanks a ton. I'll add the blackout later, but feel free to tinker around and shoot me a PR.
