### ISSUE TITLE
New version of fuzzydir is slowing down my player

### ISSUE THREAD

**Issue by da3dsoul1** [sibwaf/mpv-scripts#12]
I've been using this version of [fuzzydir.zip](https://github.com/sibwaf/mpv-scripts/files/12385468/fuzzydir.zip) , it's super responsive and fast, I decided to update it to keep up-to-date with the repo.

But latest fuzzydir.lua causes my player to load files a lot slower and it's freaking unbearable, why is this happening?
Here's a gif recording I made to show the problem:
https://github.com/sibwaf/mpv-scripts/assets/111184581/61ccdae2-4577-473b-8e51-0f1449eed06d

**Comment by AdventurerRussia** [comment]
@sibwaf 
when you finished the script then, I stayed on this version that is in the archive and did not check for updates anymore, the person above unsubscribed to me and I have the same problem with launching on your new version.
[fuzzydir.zip](https://github.com/sibwaf/mpv-scripts/files/12385529/fuzzydir.zip)

**Comment by sibwaf** [comment]
@da3dsoul1 Yeah, that looks pretty bad. Care to share some logs? `mpv --msg-level=fuzzydir=trace ...`

@AdventurerRussia The update was to fix the issue you reported - and you've confirmed it works fine. There were no changes afterwards.

**Comment by AdventurerRussia** [comment]
> 

well, I confirmed on the last version from the archive, the launch was reduced from online disks, I may not have noticed that you updated the script again ¯\_(ツ)_/¯

**Comment by da3dsoul1** [comment]
@sibwaf here you go, although I don't understand a thing in the log, hope it helps
[output.txt](https://github.com/sibwaf/mpv-scripts/files/12385830/output.txt)
Made it using this command mpv --log-file=output.txt "D:\Downloads\Torrent\Anime\[Sokudo] Shinsekai Yori [1080p BD][AV1][dual audio]\[Sokudo] Shinsekai Yori - 01 [1080p BD][AV1][dual audio].mkv

**Comment by sibwaf** [comment]
Could you please add the `--msg-level=fuzzydir=trace` parameter just so I can be sure the script doesn't try to scan something unexpected? Doesn't seem it does, but you never know.

In general it seems that Windows strikes again with it's nonsense. Just how do you implement your path traversal in a way local path scanning is slower than the remote one?..

I guess the fix would be to just launch *all* the scanning at the same time and just use the one that was the fastest. I'll try cooking up a prototype tomorrow.

**Comment by da3dsoul1** [comment]
@sibwaf where do I input this parameter? I'm not a savvy user with this stuff :C

**Comment by sibwaf** [comment]
Just before the `--log-file` parameter, so something like this:
```
mpv --msg-level=fuzzydir=trace --log-file=output.txt "D:\Downloads\Torrent\Anime\[Sokudo] Shinsekai Yori [1080p BD][AV1][dual audio]\[Sokudo] Shinsekai Yori - 01 [1080p BD][AV1][dual audio].mkv"
```

**Comment by da3dsoul1** [comment]
@sibwaf done
[output.txt](https://github.com/sibwaf/mpv-scripts/files/12385979/output.txt)

**Comment by sibwaf** [comment]
Thanks! Yep, seems normal.

Could you try out this prototype and share the log it produces? Notice - it's not a functional script version, just a quick theory test. [fuzzydir.txt](https://github.com/sibwaf/mpv-scripts/files/12388231/fuzzydir.txt) (you'll have to rename it to `fuzzydir.lua`, GitHub's funny like that)

**Comment by da3dsoul1** [comment]
@sibwaf here you go
[output.txt](https://github.com/sibwaf/mpv-scripts/files/12397201/output.txt)
It's still slow

**Comment by sibwaf** [comment]
Okay, cool (not cool). I think I found a way to implement the fix I was talking about, but it's a *big* pain. I went to look back at the issue that I was trying to solve initially - and, uh, actually it seems that the "optimization" I implemented via PowerShell didn't do much.

So, basically I disabled the "optimization" by default in the new version - so give it a spin, should be performing the same as it was in the past.

Hope it won't affect opening videos on remote shares too much (if the "optimization" even did anything in the first place). If anyone wants to volunteer checking this, you can use the `--msg-level=fuzzydir=trace --log-file=output.txt` flags to get a timestamped log and try enabling/disabling `use_powershell` in the script.

**Comment by AdventurerRussia** [comment]
@sibwaf and so I gave a friend a person who has online disks, he said that with the new version of the script that you did, the video launch became 12 seconds, on the last version that I attached in my first messages, the launch was 30 seconds, he wrote it better.
on the oldest version before my report about slow startup, the startup was generally 3 min.

**Comment by sibwaf** [comment]
@AdventurerRussia Could I ask you and your friend to try opening something on an online disk with `use_powershell = true` and `use_powershell = false` and compare which one works better just to be sure?

**Comment by da3dsoul1** [comment]
Just tried your latest updated lua from the repo and it's indeed working fine, thanks for your work!

**Comment by AdventurerRussia** [comment]
> @AdventurerRussia Could I ask you and your friend to try opening something on an online disk with `use_powershell = true` and `use_powershell = false` and compare which one works better just to be sure?

instantly became with local use_powershell = true

**Comment by sibwaf** [comment]
Became slower, I presume? Welp, guess the old fix was a big waste of time.

**Comment by AdventurerRussia** [comment]
> Became slower, I presume? Welp, guess the old fix was a big waste of time.

no, it began to open as quickly as possible with the settings enabled, as a person unsubscribed to me. It was off for about 15 seconds
now the script works perfectly, the player opens perfectly!
You did a good job, thank you for taking the time to finalize

**Comment by AdventurerRussia** [comment]
a friend wrote to me and complained that in my build, running a video from a regular disk for 6 seconds, they found by brute force that because of the new script, turning powershell on and off did not give anything, I still have the old script that I attached in the comments, the video launch is fast there, in short, it's very strange because everything is fine with me it runs like another person who has online disks. But this other friend has a long launch from regular disks. Nothing needs to be fixed already, but an interesting observation is that a long startup is now possible from a regular disk.
he just bought a new computer and discovered it, everything was fine on the last computer.
though the new computer already has windows 11 instead of 10
[fuzzydir.zip](https://github.com/sibwaf/mpv-scripts/files/12540095/fuzzydir.zip)
