### ISSUE TITLE
blackout.lua add to readme watch-later-options-remove=contrast if using save-position-on-quit

### ISSUE THREAD

**Issue by mrfragger** [sibwaf/mpv-scripts#13]
If using save-position-on-quit which resumes video and audio playback from position last played.  From an average user's viewpoint if they hit the blackout key and then for who knows what reason just close out the video.  Next time they go to play that video they won't be able to view it and think something is broken.  Even if they toggle blackout key the contrast -100 has been remembered for that particular video and only way to rectify it is pressing 2 and holding it down till it gets contrast back to 0.  So to avoid all that headache just set the following.  Thanks a ton for the script.  

mpv.conf
```
save-position-on-quit #resumes playback
# blackout.lua will restore video if mpv is closed during a blackout
watch-later-options-remove=contrast 
```

bosskey is ok and doesn't have this issue but no wayland and requires install another app for linux is a no-go as I'm trying to compile a working mac, linux, windows script compilation and pretty much set it up and ready to go for the average user.

also update readme
Notice: this script relies on setting saturation to the lowest possible value, effectively making video just black.
Notice: this script relies on setting contrast to the lowest possible value, effectively making video just black.

**Comment by sibwaf** [comment]
Hm, not sure about just putting it in the readme. I'd rather have it automated somehow - maybe with an `on-exit` hook or something. I'll try cooking something up on the weekend.

**Comment by mrfragger** [comment]
Ok sweet also this should also if possible be accounted for.
`watch-later-options-remove=pause`

I think someone playing music hit's blackout a music file or movie and closes out expects it to start playing once they open it up again.

Maybe can use some of this code...no idea...kinda over my head.
https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/pause-when-minimize.lua

```
-- This script pauses playback when minimizing the window, and resumes playback
-- if it's brought back again. If the player was already paused when minimizing,
-- then try not to mess with the pause state.

local did_minimize = false

mp.observe_property("window-minimized", "bool", function(name, value)
    local pause = mp.get_property_native("pause")
    if value == true then
        if pause == false then
            mp.set_property_native("pause", true)
            did_minimize = true
        end
    elseif value == false then
        if did_minimize and (pause == true) then
            mp.set_property_native("pause", false)
        end
        did_minimize = false
    end
end)
```

**Comment by sibwaf** [comment]
Care to give this a spin? [blackout.zip](https://github.com/sibwaf/mpv-scripts/files/12777592/blackout.zip)

Can't say it's the ideal implementation (if you changed the subtitle track or contrast/whatever, then activated blackout, and then quit, it will ignore whatever values you changed and just play it with the default values next time), but I didn't manage to find a way to reset the values just before the watch-later stuff saves everything. So, this will have to do.

I don't think removing `pause` from saved properties is a good idea as it would be modifying the default mpv behavior (it saves the pause state), so I'm skipping it.

**Comment by mrfragger** [comment]
new blackout.zip works perectly.  Well done.  As for it not pausing on startup I just use this script and it does the trick.

```
-- unpauser.lua
--
-- Always unpause mpv when a new file is loaded.

mp.add_hook("on_load", 5, function ()
    if(mp.get_property_bool("pause") == true) then
        mp.set_property_bool("pause", false)
    end
end)
```
