### ISSUE TITLE
reload.lua issue

### ISSUE THREAD

**Issue by uugaabuugaa** [sibwaf/mpv-scripts#16]
On mpvnet the script seems to work but on regular mpv this error is showing.

```
[reload] The loadfile option must be an integer: start=367.96
[reload] Command loadfile: argument index can't be parsed: option parameter could not be parsed.
```

I don't know why mpvnet works but I'm guessing something to make the script consider only start=367 instead of 367.96 should work but don't know how to.

**Comment by sibwaf** [comment]
Ugh, mpv decided to make a non-backward-compatible change to the `loadfile` command in 0.38, wonderful.

Could you try this version in both mpv (which is broken for you now) and mpvnet (which is not broken for you now)? I'd rather to try keeping compatibility with the old versions.

```lua
--[[
	reload / by sibwaf / https://github.com/sibwaf/mpv-scripts

	Reopens the current playing file and seeks to the same timestamp on a button press ([Shift+R] by default).
    Useful for situations when you are watching YouTube/streams and your connection breaks for some reason.

	MIT license - do whatever you want, but I'm not responsible for any possible problems.
	Please keep the URL to the original repository. Thanks!
]]

local mp = require("mp")

local function reload()
    local path = mp.get_property("path")
    if path ~= nil then
        local time = mp.get_property_number("time-pos")
        mp.commandv("loadfile", path, "replace", -1, "start=" .. time)
    end
end

mp.add_key_binding("R", "reload", reload)
```

**Comment by uugaabuugaa** [comment]
> ```
> 
> local mp = require("mp")
> 
> local function reload()
>     local path = mp.get_property("path")
>     if path ~= nil then
>         local time = mp.get_property_number("time-pos")
>         mp.commandv("loadfile", path, "replace", -1, "start=" .. time)
>     end
> end
> 
> mp.add_key_binding("R", "reload", reload)
> ```

This one works in mpv. Thanks a lot! And although I've stopped using mpvnet, since you asked it shows this error now.

```
[reload] Expected '=' and a value.
[reload] Command loadfile: argument options can't be parsed: option parameter could not be parsed.
```

**Comment by sibwaf** [comment]
Would you mind checking if this version is any better in terms of compatibility?

```lua
--[[
    reload / by sibwaf / https://github.com/sibwaf/mpv-scripts

    Reopens the current playing file and seeks to the same timestamp on a button press ([Shift+R] by default).
    Useful for situations when you are watching YouTube/streams and your connection breaks for some reason.

    MIT license - do whatever you want, but I'm not responsible for any possible problems.
    Please keep the URL to the original repository. Thanks!
]]

local mp = require("mp")

local function reload()
    local path = mp.get_property("path")
    if path ~= nil then
        local args = {}
        args["name"] = "loadfile"
        args["url"] = path
        args["flags"] = "replace"
        args["options"] = "start=" .. mp.get_property_number("time-pos")
        mp.command_native(args)
    end
end

mp.add_key_binding("R", "reload", reload)
```

**Comment by uugaabuugaa** [comment]
> ```
> local mp = require("mp")
> 
> local function reload()
>     local path = mp.get_property("path")
>     if path ~= nil then
>         local args = {}
>         args["name"] = "loadfile"
>         args["url"] = path
>         args["flags"] = "replace"
>         args["options"] = "start=" .. mp.get_property_number("time-pos")
>         mp.command_native(args)
>     end
> end
> 
> mp.add_key_binding("R", "reload", reload)
> ```

This is it. Works on both mpv and mpvnet.

**Comment by sibwaf** [comment]
Cool. Thanks for testing!
