### ISSUE TITLE
fuzzydir.lua not working anymore

### ISSUE THREAD

**Issue by Fuwiz** [sibwaf/mpv-scripts#18]
Used it for 2 years and now when i updated mpv it not working anymore.
In mpv.conf i have: sub-file-paths=**
Version: mpv v0.39.0-386-g2d813de6 (on windows 10)
log: no errors

**Comment by Fuwiz** [comment]
Script only get subtitles now if they in same folder as video. If in other folder - no.

**Comment by sibwaf** [comment]
Just checked - still works for me on mpv 0.39 (linux). Check if you're using the latest script version.

Nothing I can really say unless you provide verbose fuzzydir logs (`mpv --msg-level=fuzzydir=trace path-to-video-here`)

**Comment by Fuwiz** [comment]
> Just checked - still works for me on mpv 0.39 (linux). Check if you're using the latest script version.
> 
> Nothing I can really say unless you provide verbose fuzzydir logs (`mpv --msg-level=fuzzydir=trace path-to-video-here`)

PS C:\Windows\system32> mpv --msg-level=fuzzydir=trace path-to-video-here
[fuzzydir] Loading lua script C:\Users\User\AppData\Roaming/mpv/scripts/fuzzydir.lua...
[fuzzydir] loading mp.defaults
[fuzzydir] loading file C:\Users\User\AppData\Roaming/mpv/scripts/fuzzydir.lua
[fuzzydir] reading options for fuzzydir
[fuzzydir] script-opts/fuzzydir.conf not found.
[fuzzydir] lua-settings/fuzzydir.conf not found.
[fuzzydir] PowerShell version -1
[file] Cannot open file 'path-to-video-here': No such file or directory
Failed to open path-to-video-here.
Exiting... (Errors when loading file)
[fuzzydir] Exiting...

**Comment by Fuwiz** [comment]
> Just checked - still works for me on mpv 0.39 (linux). Check if you're using the latest script version.
> 
> Nothing I can really say unless you provide verbose fuzzydir logs (`mpv --msg-level=fuzzydir=trace path-to-video-here`)

C:\Windows\System32>cd C:\Users\User\Downloads\qBittorent\Mousou Dairinin [BD 1080p]

C:\Users\User\Downloads\qBittorent\Mousou Dairinin [BD 1080p]>mpv --msg-level=fuzzydir=trace path-to-video-here
[fuzzydir] Loading lua script C:\Users\User\AppData\Roaming/mpv/scripts/fuzzydir.lua...
[fuzzydir] loading mp.defaults
[fuzzydir] loading file C:\Users\User\AppData\Roaming/mpv/scripts/fuzzydir.lua
[fuzzydir] reading options for fuzzydir
[fuzzydir] script-opts/fuzzydir.conf not found.
[fuzzydir] lua-settings/fuzzydir.conf not found.
[fuzzydir] PowerShell version -1
[file] Cannot open file 'path-to-video-here': No such file or directory
Failed to open path-to-video-here.
Exiting... (Errors when loading file)
[fuzzydir] Exiting...

Im not sure if i did properly what you ask

**Comment by sibwaf** [comment]
Nope. Replace "path-to-video-here" with an actual filename.

**Comment by Fuwiz** [comment]
> Nope. Replace "path-to-video-here" with an actual filename.

C:\Users\User\Downloads\qBittorent\Mousou Dairinin [BD 1080p]>mpv --msg-level=fuzzydir=trace "Mousou Dairinin 01.mkv"
[fuzzydir] Loading lua script C:\Users\User\AppData\Roaming/mpv/scripts/fuzzydir.lua...
[fuzzydir] loading mp.defaults
[fuzzydir] loading file C:\Users\User\AppData\Roaming/mpv/scripts/fuzzydir.lua
[fuzzydir] reading options for fuzzydir
[fuzzydir] script-opts/fuzzydir.conf not found.
[fuzzydir] lua-settings/fuzzydir.conf not found.
[fuzzydir] PowerShell version -1
Resuming playback. This behavior can be disabled with --no-resume-playback.
● Video  --vid=1               (h264 1920x1080 23.976 fps) [default]
● Audio  --aid=1  --alang=jpn  'FLAC 2.0' (flac 2ch 48000 Hz) [default]
● Subs   --sid=1  --slang=eng  'English Subtitle' (subrip) [default]
File tags:
 Title: [a4e]Paranoia Agent - 01 - ENTER LIL' SLUGGER
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p10
(Paused) AV: 00:00:02 / 00:24:33 (0%) A-V:  0.000

![2024-12-05 (02-32-05 680) explorer - Mousou_Dairinin_ BD_1080p](https://github.com/user-attachments/assets/5b0ea442-7a80-4a32-aba4-7f88aee22674)
![2024-12-05 (02-32-08 349) explorer - Sub_ Praded_ _Bella](https://github.com/user-attachments/assets/c2df7dc4-af30-46ee-9bec-19d648574dc9)

Subs in this folder dont want to load

**Comment by Fuwiz** [comment]
I tested older version of mpv from sourceforge and this script works (mpv-x86_64-20231126-git-6898d57). Problem in new version of mpv

**Comment by sibwaf** [comment]
Judging by the logs it seems that the `on_load` hook doesn't get called by the player - basically, the script is loaded but the main logic doesn't get called by the the player when you open the video so nothing happens. We would've seen a message like `max_search_depth = ...` in logs if it was actually called.

You can read about the hook here if you're interested: https://mpv.io/manual/stable/#command-interface-on-load

It is a problem with your mpv distribution (AFAIK mpv still doesn't provide any Windows binaries - all of those are unofficial and are built by enthusiasts), so you should report this (the fact that `on_load` hook is not being called) to the people you got the binaries from. There is nothing I can or should do with the script to make a workaround as your player distribution is broken.

You should also have an option of switching to a different Windows mpv distribution - I do remember there were multiple people building different binaries in the past.

Considering the fact it is not a problem with the script (or it's compatibility with a newer version of mpv as it works as expected with the latest mainline linux mpv release) I'm closing this issue. Do feel free to reopen it if switching the mpv distribution doesn't help and all Windows mpv distribution maintainers provide proof that the `on_load` hook actually works.
